//
//  Fonts.swift
//  pisiffik_ios
//
//  Created by Haider Ali on 27/05/2022.
//  Copyright © 2022 softwareAlliance. All rights reserved.
//

import Foundation


struct Fonts {
    
    static let regularFontsSize10 = R.font.sfProTextRegular(size: 10)
    static let regularFontsSize12 = R.font.sfProTextRegular(size: 12)
    static let regularFontsSize13 = R.font.sfProTextRegular(size: 13)
    static let regularFontsSize14 = R.font.sfProTextRegular(size: 14)
    static let regularFontsSize15 = R.font.sfProTextRegular(size: 15)
    static let regularFontsSize16 = R.font.sfProTextRegular(size: 16)
    static let regularFontsSize17 = R.font.sfProTextRegular(size: 17)
    static let regularFontsSize18 = R.font.sfProTextRegular(size: 18)
    static let regularFontsSize19 = R.font.sfProTextRegular(size: 19)
    static let regularFontsSize20 = R.font.sfProTextRegular(size: 20)
    static let regularFontsSize21 = R.font.sfProTextRegular(size: 21)
    static let regularFontsSize22 = R.font.sfProTextRegular(size: 22)
    static let regularFontsSize23 = R.font.sfProTextRegular(size: 23)
    static let regularFontsSize24 = R.font.sfProTextRegular(size: 24)
    static let regularFontsSize25 = R.font.sfProTextRegular(size: 25)
    static let regularFontsSize26 = R.font.sfProTextRegular(size: 26)
    static let regularFontsSize27 = R.font.sfProTextRegular(size: 27)
    static let regularFontsSize28 = R.font.sfProTextRegular(size: 28)
    
    static let mediumFontsSize10 = R.font.sfProTextMedium(size: 10)
    static let mediumFontsSize12 = R.font.sfProTextMedium(size: 12)
    static let mediumFontsSize13 = R.font.sfProTextMedium(size: 13)
    static let mediumFontsSize14 = R.font.sfProTextMedium(size: 14)
    static let mediumFontsSize15 = R.font.sfProTextMedium(size: 15)
    static let mediumFontsSize16 = R.font.sfProTextMedium(size: 16)
    static let mediumFontsSize17 = R.font.sfProTextMedium(size: 17)
    static let mediumFontsSize18 = R.font.sfProTextMedium(size: 18)
    static let mediumFontsSize19 = R.font.sfProTextMedium(size: 19)
    static let mediumFontsSize20 = R.font.sfProTextMedium(size: 20)
    static let mediumFontsSize21 = R.font.sfProTextMedium(size: 21)
    static let mediumFontsSize22 = R.font.sfProTextMedium(size: 22)
    static let mediumFontsSize23 = R.font.sfProTextMedium(size: 23)
    static let mediumFontsSize24 = R.font.sfProTextMedium(size: 24)
    static let mediumFontsSize25 = R.font.sfProTextMedium(size: 25)
    static let mediumFontsSize26 = R.font.sfProTextMedium(size: 26)
    static let mediumFontsSize27 = R.font.sfProTextMedium(size: 27)
    static let mediumFontsSize28 = R.font.sfProTextMedium(size: 28)
    static let mediumFontsSize32 = R.font.sfProTextMedium(size: 32)
    
    static let semiBoldFontsSize12 = R.font.sfProTextSemibold(size: 12)
    static let semiBoldFontsSize13 = R.font.sfProTextSemibold(size: 13)
    static let semiBoldFontsSize14 = R.font.sfProTextSemibold(size: 14)
    static let semiBoldFontsSize15 = R.font.sfProTextSemibold(size: 15)
    static let semiBoldFontsSize16 = R.font.sfProTextSemibold(size: 16)
    static let semiBoldFontsSize17 = R.font.sfProTextSemibold(size: 17)
    static let semiBoldFontsSize18 = R.font.sfProTextSemibold(size: 18)
    static let semiBoldFontsSize19 = R.font.sfProTextSemibold(size: 19)
    static let semiBoldFontsSize20 = R.font.sfProTextSemibold(size: 20)
    static let semiBoldFontsSize21 = R.font.sfProTextSemibold(size: 21)
    static let semiBoldFontsSize22 = R.font.sfProTextSemibold(size: 22)
    static let semiBoldFontsSize23 = R.font.sfProTextSemibold(size: 23)
    static let semiBoldFontsSize24 = R.font.sfProTextSemibold(size: 24)
    static let semiBoldFontsSize25 = R.font.sfProTextSemibold(size: 25)
    static let semiBoldFontsSize26 = R.font.sfProTextSemibold(size: 26)
    static let semiBoldFontsSize27 = R.font.sfProTextSemibold(size: 27)
    static let semiBoldFontsSize28 = R.font.sfProTextSemibold(size: 28)
    static let semiBoldFontsSize36 = R.font.sfProTextSemibold(size: 36)
    static let semiBoldFontsSize48 = R.font.sfProTextSemibold(size: 48)
    
    static let boldFontsSize10 = R.font.sfProTextBold(size: 10)
    static let boldFontsSize11 = R.font.sfProTextBold(size: 11)
    static let boldFontsSize12 = R.font.sfProTextBold(size: 12)
    static let boldFontsSize13 = R.font.sfProTextBold(size: 13)
    static let boldFontsSize14 = R.font.sfProTextBold(size: 14)
    static let boldFontsSize15 = R.font.sfProTextBold(size: 15)
    static let boldFontsSize16 = R.font.sfProTextBold(size: 16)
    static let boldFontsSize17 = R.font.sfProTextBold(size: 17)
    static let boldFontsSize18 = R.font.sfProTextBold(size: 18)
    static let boldFontsSize19 = R.font.sfProTextBold(size: 19)
    static let boldFontsSize20 = R.font.sfProTextBold(size: 20)
    static let boldFontsSize21 = R.font.sfProTextBold(size: 21)
    static let boldFontsSize22 = R.font.sfProTextBold(size: 22)
    static let boldFontsSize23 = R.font.sfProTextBold(size: 23)
    static let boldFontsSize24 = R.font.sfProTextBold(size: 24)
    static let boldFontsSize25 = R.font.sfProTextBold(size: 25)
    static let boldFontsSize26 = R.font.sfProTextBold(size: 26)
    static let boldFontsSize27 = R.font.sfProTextBold(size: 27)
    static let boldFontsSize28 = R.font.sfProTextBold(size: 28)
    static let boldFontsSize30 = R.font.sfProTextBold(size: 30)
    
    static let boldFontsSize44 = R.font.sfProTextBold(size: 44)
    
    
    static let regularItalicFontsSize12 = R.font.sfProDisplayRegularItalic(size: 12)
    static let regularItalicFontsSize13 = R.font.sfProDisplayRegularItalic(size: 13)
    static let regularItalicFontsSize14 = R.font.sfProDisplayRegularItalic(size: 14)
    static let regularItalicFontsSize15 = R.font.sfProDisplayRegularItalic(size: 15)
    static let regularItalicFontsSize16 = R.font.sfProDisplayRegularItalic(size: 16)
    static let regularItalicFontsSize17 = R.font.sfProDisplayRegularItalic(size: 17)
    static let regularItalicFontsSize18 = R.font.sfProDisplayRegularItalic(size: 18)
    static let regularItalicFontsSize19 = R.font.sfProDisplayRegularItalic(size: 19)
    static let regularItalicFontsSize20 = R.font.sfProDisplayRegularItalic(size: 20)
    static let regularItalicFontsSize21 = R.font.sfProDisplayRegularItalic(size: 21)
    static let regularItalicFontsSize22 = R.font.sfProDisplayRegularItalic(size: 22)
    static let regularItalicFontsSize23 = R.font.sfProDisplayRegularItalic(size: 23)
    static let regularItalicFontsSize24 = R.font.sfProDisplayRegularItalic(size: 24)
    static let regularItalicFontsSize25 = R.font.sfProDisplayRegularItalic(size: 25)
    static let regularItalicFontsSize26 = R.font.sfProDisplayRegularItalic(size: 26)
    static let regularItalicFontsSize27 = R.font.sfProDisplayRegularItalic(size: 27)
    static let regularItalicFontsSize28 = R.font.sfProDisplayRegularItalic(size: 28)
    
}
